language: node_js

node_js:
  - "6"
  - "5"
  - "4"
  - "node"
  - "iojs"


dist: xenial

env:
  - CC=clang CXX=clang++ npm_config_clang=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
